### ISSUE TITLE
cli "deployments" rationale (and _user_dir breaking docker)

### ISSUE THREAD

**Issue by sanzoghenzo** [mamba-org/quetz#216]
**TL;DR**: if I run `quetz run` in a docker container without a user directory, the container exits with a permission error while trying to create the directory `/nonexistent/.config/quetz` in which to place the `deployments,json` file.
I'm wondering if this config file is needed at all. 

This is my Dockerfile, that builds the latest git version of quetz and runs it with the option added with #212:

```dockerfile
FROM condaforge/miniforge3:latest as base

WORKDIR build
ARG CONDA_ENV=/opt/venv
COPY environment.yml .
RUN conda env create -p $CONDA_ENV -f environment.yml
COPY pyproject.toml setup.py LICENSE ./
COPY quetz ./quetz
RUN conda run -p $CONDA_ENV pip install . --no-deps

FROM gcr.io/distroless/base-debian10 as production
ARG CONDA_ENV=/opt/venv
ENV LANG=en_US.UTF-8
ENV PATH $CONDA_ENV/bin:$PATH
COPY --from=base $CONDA_ENV $CONDA_ENV
USER nobody
WORKDIR /deployment
ENTRYPOINT ["quetz"]
CMD ["run", ".", "--skip-if-exists"]
```

as you can see the working directory is set to `/deployment` and the default command tries to run the deployment in the current directory, if it finds a `config.toml` in it.

with a `docker-compose.yml` like this:
```yml
version: "3.8"

services:
  quetz:
    image: "quetz:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: quetz
    ports:
      - "8000:8000"
    volumes:
      - "./deployment:/deployment"
```
I can mount a local deployment directory with the `config.toml` in it.

the aformentioned error is originated by the[`_get_deployments` function](https://github.com/mamba-org/quetz/blob/master/quetz/cli.py#L264) that tries to create the directory in which to place the config file.

this file is only used to keep track of existing deployments, but I don't think it's useful in a docker context;
I suppose that the (non)existence check can be better performed by looking at the actual files and directories inside the deployment folder.

If it's ok with you I'm going to try to fix the issue by removing this file.

Maybe we should try to better define the cli commands, but I think it's already mentioned in #155
